/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jamie' at '12/01/17 21:28' with Gradle 3.0
 *
 * @author Jamie, @date 12/01/17 21:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
